USE [video-games]

CREATE TABLE games (
    GAME_ID INT PRIMARY KEY IDENTITY(1,1),
    IMG TEXT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONSOLE VARCHAR(10) NOT NULL,
    GENRE VARCHAR(50) NOT NULL,
    PUBLISHER VARCHAR(100) NOT NULL,
    DEVELOPER VARCHAR(100) NOT NULL,
    CRITIC_SCORE FLOAT NOT NULL,
    TOTAL_SALES FLOAT NOT NULL,
    NA_SALES FLOAT NOT NULL,
    JP_SALES FLOAT NOT NULL,
    PAL_SALES FLOAT NOT NULL,
    OTHER_SALES FLOAT NOT NULL,
    RELEASED_DATE DATE NOT NULL,
    LAST_UPDATED DATE NOT NULL 
);